language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - android-21
    - android-20
    - android-19
    - android-18
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22
#    - sys-img-armeabi-v7a-android-18
#    - sys-img-armeabi-v7a-android-19
#    - sys-img-armeabi-v7a-android-20
#    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
jdk:
  - oraclejdk8
before_script:
 - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew connectedCheck